# 기능 관련 
- name: feat
  color: 1D76DB
  description: 새로운 기능 추가

- name: enhancement
  color: A2EEEF
  description: 기존 기능 개선

- name: fix
  color: D73A4A
  description: 기능 오류 또는 예외 발생

- name: refactor
  color: FFD700
  description: 리팩토링 (기능 변화 없음)

- name: perf
  color: FBCA04
  description: 성능 개선

- name: style
  color: EDEDED
  description: 코드 스타일/포맷 관련 변경

# 문서 / 콘텐츠
- name: docs
  color: 006B75
  description: 문서 수정 또는 추가

- name: contribute
  color: 0366D6
  description: 콘텐츠 기여

# 작업 상태
- name: in progress
  color: BFDADC
  description: 작업 진행 중

- name: ready
  color: 0E8A16
  description: 리뷰 가능 상태

- name: blocked
  color: B60205
  description: 외부 요인으로 작업 중단됨

# 우선순위
- name: priority: high
  color: FF0000
  description: 우선 처리 필요

- name: priority: low
  color: CCCCCC
  description: 낮은 우선순위

# 유지보수 / 기타
- name: chore
  color: F9D0C4
  description: 빌드/CI/환경 설정 관련 작업

- name: build
  color: 5319E7
  description: 빌드 설정 또는 외부 종속성 변경

- name: test
  color: FEF2C0
  description: 테스트 코드 관련 작업

- name: dependencies
  color: 1B1F23
  description: 패키지 의존성 변경